String SPLASH_SCREEN = 'SPLASH_SCREEN';
String HOME_SCREEN = 'HOME_SCREEN';
String PLACES_INFO_SCREEN = 'PLACES_INFO_SCREEN';
String PRIVACY_SCREEN = 'PRIVACY_POLICY_SCREEN';
String CONTACT_SCREEN = 'CONTACT_SCREEN';
String REVIEW_SCREEN = 'REVIEW_SCREEN';
String REVIEW_FORM = 'REVIEW_FORM';
String BOOK_PLACES_SCREEN = 'BOOK_PLACES_SCREEN';